# Generated by Django 3.0.5 on 2020-04-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='images/iconos/default.png', max_length=500)),
                ('posicion', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(blank=True)),
                ('hora_fin', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('programa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvguia_app.Programa')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
            ],
            bases=('tvguia_app.programa',),
        ),
        migrations.CreateModel(
            name='Documental',
            fields=[
                ('programa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvguia_app.Programa')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True)),
                ('edad', models.IntegerField(default=0)),
                ('puntuacion', models.IntegerField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
            ],
            bases=('tvguia_app.programa',),
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('programa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvguia_app.Programa')),
                ('Titulo', models.CharField(max_length=100, unique=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
            ],
            bases=('tvguia_app.programa',),
        ),
        migrations.CreateModel(
            name='Otro',
            fields=[
                ('programa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvguia_app.Programa')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
            ],
            bases=('tvguia_app.programa',),
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('programa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvguia_app.Programa')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True)),
                ('edad', models.IntegerField(default=0)),
                ('puntuacion', models.IntegerField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
            ],
            bases=('tvguia_app.programa',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('programa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvguia_app.Programa')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True)),
                ('edad', models.IntegerField(default=0)),
                ('puntuacion', models.IntegerField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
            ],
            bases=('tvguia_app.programa',),
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('numero', models.IntegerField(null=True)),
                ('temporada', models.IntegerField(null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serie_episodio', to='tvguia_app.Serie')),
            ],
        ),
    ]
