# Generated by Django 3.0.5 on 2020-04-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(max_length=500, null=True)),
                ('posicion', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(blank=True)),
                ('hora_fin', models.DateTimeField(blank=True)),
                ('duracion_total', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('edad', models.IntegerField(default=0)),
                ('puntuacion', models.IntegerField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
                ('temporada', models.CharField(default='NONE', max_length=500, null=True)),
                ('tipo', models.CharField(choices=[('otros', '0'), ('pelicula', '1'), ('serie', '2'), ('noticia', '3'), ('documental', '4'), ('deporte', '5'), ('infantil', '6')], default='otros', max_length=100)),
                ('canal_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canal_programa', to='tvguia_app.Canal')),
            ],
            options={
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('edad', models.IntegerField(default=0)),
                ('puntuacion', models.IntegerField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
                ('programa_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_serie', to='tvguia_app.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('edad', models.IntegerField(default=0)),
                ('puntuacion', models.IntegerField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
                ('programa_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_pelicula', to='tvguia_app.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Otro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
                ('programa_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_otro', to='tvguia_app.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
                ('programa_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_noticias', to='tvguia_app.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('numero', models.IntegerField(null=True)),
                ('temporada', models.IntegerField(null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serie_episodio', to='tvguia_app.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Documental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('edad', models.IntegerField(default=0)),
                ('puntuacion', models.IntegerField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
                ('programa_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_documental', to='tvguia_app.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('imagen', models.CharField(max_length=500, null=True)),
                ('programa_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_deporte', to='tvguia_app.Programa')),
            ],
        ),
    ]
