# Generated by Django 3.0.5 on 2020-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvguia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='icono',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
