# Generated by Django 3.0.5 on 2020-04-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvguia_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='duracion',
        ),
        migrations.AlterField(
            model_name='programa',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
