# Generated by Django 3.0.5 on 2020-04-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvguia_app', '0003_auto_20200413_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documental',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='fecha',
        ),
    ]
